[package]
name = "tvrank"
description = "Query information about movies and series"
version = "0.1.0"
edition = "2018"
authors = ["Fred Morcos <fm@fredmorcos.com>"]
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tvrank"
path = "src/lib.rs"

[[bin]]
name = "tvrank"
path = "src/main.rs"

[dependencies]
env_logger = "0.8"
log = "0.4"
structopt = "0.3"
derive_more = "0.99"
derive-new = "0.5"
enum-utils = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.9"
serde_json = "1.0"
csv = "1.1"
regex = "1.5"
directories = "3.0"
memmap = "0.7"
flate2 = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
atoi = "0.4"
fnv = "1.0"

[profile.release]
debug = true
panic = "abort"
codegen-units = 1
lto = true
