[workspace]
members = ["lib", "cli"]
default-members = ["lib", "cli"]

[profile.release]
debug = false
lto = true

[profile.production]
inherits = "release"
codegen-units = 1
opt-level = 3
incremental = false
overflow-checks = false
panic = "abort"
