[package]
name = "tvrank"
description = "Download information about movies and series"
version = "0.1.0"
edition = "2018"
authors = ["Fred Morcos <fm@fredmorcos.com>"]
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
env_logger = "0.8"
log = "0.4"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
derive-new = "0.5"
reqwest = "0.11"
